import Head from "next/head";
import Desktop from "../components/desktop/Desktop";
import Taskbar from "../components/taskbar/Taskbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Windows 11</title>
        {/* Meta tags dynamically generated by metaSEO (https://metaseo.itsvg.in) */}
        <link rel="icon" href="/logo.png" />
        <meta name="title" content="Windows 11" />
        <meta
          name="description"
          content="Windows 11 made with 💛 using NextJS and TailwindCSS by Vishwa Gaurav."
        />
        <meta name="copyright" content="VishwaGauravIn" />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://win.itsvg.in" />
        <meta property="og:title" content="Windows 11" />
        <meta
          property="og:description"
          content="Windows 11 made with 💛 using NextJS and TailwindCSS by Vishwa Gaurav."
        />
        <meta property="og:image" content="https://win.itsvg.in/webimg.png" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://win.itsvg.in" />
        <meta property="twitter:title" content="Windows 11" />
        <meta
          property="twitter:description"
          content="Windows 11 made with 💛 using NextJS and TailwindCSS by Vishwa Gaurav."
        />
        <meta
          property="twitter:image"
          content="https://win.itsvg.in/webimg.png"
        />
        {/* Google Analytics */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-W11XMFPKX7"
        />

        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-W11XMFPKX7', { page_path: window.location.pathname });
            `,
          }}
        />
      </Head>

      <body className="text-white h-[864px] w-[1536px]">
        <Desktop />
        <Taskbar />
      </body>
    </>
  );
}
