import Head from 'next/head'
import Desktop from '../components/desktop/Desktop'
import Taskbar from '../components/taskbar/Taskbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className="text-white">
        <Desktop/>
        <Taskbar/>
      </body>
    </>
  )
}
